Repository jorgecarleitao/parquet2, pull requests merged in 2021-09, with the labels that each got.

#48 Compression enum typo
  src/compression.rs
  src/parquet_bridge.rs
Labels: backwards-incompatible

#49 Add `null_count` method to trait `Statistics`
  .gitignore
  src/statistics/binary.rs
  src/statistics/boolean.rs
  src/statistics/fixed_len_binary.rs
  src/statistics/mod.rs
  src/statistics/primitive.rs
Labels: enhancement

#53 Fixed error in reading zero-width bit from hybrid RLE.
  src/encoding/hybrid_rle/decoder.rs
  src/encoding/hybrid_rle/mod.rs
Labels: bug
