Repository jorgecarleitao/parquet2, pull requests merged in 2022-06, with the labels that each got.

#147 Added API to write sidecar
  examples/write_sidecar.rs
  guide/src/README.md
  src/write/file.rs
  src/write/mod.rs
  tests/it/write/mod.rs
  tests/it/write/sidecar.rs
Labels: feature

#148 Fixed missing re-export of `FileMetaData` to allow using side-car API
  src/indexes/mod.rs
  src/lib.rs
  src/metadata/file_metadata.rs
  src/metadata/mod.rs
  src/page/mod.rs
  src/parquet_bridge.rs
  src/schema/mod.rs
  src/statistics/mod.rs
  src/write/file.rs
Labels: bug

#149 Removed `AsyncSeek` requirement from page stream
  src/page/page_dict/mod.rs
  src/read/metadata.rs
  src/read/mod.rs
  src/read/page/mod.rs
  src/read/page/stream.rs
  src/read/stream.rs
Labels: enhancement

#150 Removed panics on read
  Cargo.toml
  examples/read_metadata.rs
  src/deserialize/binary.rs
  src/deserialize/boolean.rs
  src/deserialize/fixed_len.rs
  src/deserialize/native.rs
  src/deserialize/utils.rs
  src/encoding/bitpacking.rs
  src/encoding/hybrid_rle/decoder.rs
  src/encoding/mod.rs
  src/encoding/plain_byte_array.rs
  src/metadata/column_chunk_metadata.rs
  src/metadata/file_metadata.rs
  src/page/mod.rs
  src/page/page_dict/binary.rs
  src/page/page_dict/fixed_len_binary.rs
  src/page/page_dict/primitive.rs
  src/read/page/reader.rs
  src/read/page/stream.rs
  src/schema/io_thrift/from_thrift.rs
  tests/it/read/binary.rs
  tests/it/read/boolean.rs
  tests/it/read/fixed_binary.rs
  tests/it/read/mod.rs
  tests/it/read/primitive.rs
  tests/it/read/primitive_nested.rs
  tests/it/read/struct_.rs
  tests/it/read/utils.rs
Labels: bug

#153 Reduced reallocations
  src/read/compression.rs
  src/read/page/reader.rs
Labels: enhancement
