Repository jorgecarleitao/parquet2, pull requests merged in 2022-08, with the labels that each got.

#160 Delay deserialization of dictionary pages
  examples/read_metadata.rs
  src/compression.rs
  src/deserialize/binary.rs
  src/deserialize/boolean.rs
  src/deserialize/fixed_len.rs
  src/deserialize/native.rs
  src/page/mod.rs
  src/page/page_dict/binary.rs
  src/page/page_dict/fixed_len_binary.rs
  src/page/page_dict/mod.rs
  src/read/compression.rs
  src/read/mod.rs
  src/read/page/indexed_reader.rs
  src/read/page/mod.rs
  src/read/page/reader.rs
  src/read/page/stream.rs
  src/write/compression.rs
  src/write/page.rs
  tests/it/main.rs
  tests/it/read/binary.rs
  tests/it/read/dictionary/binary.rs
  tests/it/read/dictionary/fixed_len_binary.rs
  tests/it/read/dictionary/mod.rs
  tests/it/read/dictionary/primitive.rs
  tests/it/read/fixed_binary.rs
  tests/it/read/lz4_legacy.rs
  tests/it/read/mod.rs
  tests/it/read/primitive.rs
  tests/it/read/primitive_nested.rs
  tests/it/write/binary.rs
  tests/it/write/indexes.rs
  tests/it/write/mod.rs
  tests/it/write/primitive.rs
Labels: backwards-incompatible

#168 Simplified interal code
  src/indexes/mod.rs
  src/metadata/sort.rs
  src/read/metadata.rs
  src/read/page/reader.rs
  src/read/stream.rs
  src/schema/io_message/from_message.rs
  src/statistics/binary.rs
  src/statistics/boolean.rs
  src/statistics/fixed_len_binary.rs
  src/statistics/primitive.rs
Labels: enhancement

#170 Privatized `CompressionLevel`
  src/compression.rs
  src/parquet_bridge.rs
Labels: backwards-incompatible

#171 Made `compute_page_row_intervals` public
  src/indexes/intervals.rs
Labels: enhancement

#172 Fixed OOM on malicious/malformed thrift
  Cargo.toml
  examples/read_metadata.rs
  src/bloom_filter/read.rs
  src/error.rs
  src/indexes/index.rs
  src/indexes/intervals.rs
  src/lib.rs
  src/metadata/column_chunk_metadata.rs
  src/metadata/file_metadata.rs
  src/metadata/row_metadata.rs
  src/metadata/schema_descriptor.rs
  src/read/compression.rs
  src/read/indexes/deserialize.rs
  src/read/indexes/read.rs
  src/read/metadata.rs
  src/read/mod.rs
  src/read/page/indexed_reader.rs
  src/read/page/reader.rs
  src/read/page/stream.rs
  src/read/stream.rs
  src/schema/io_message/from_message.rs
  src/schema/io_thrift/from_thrift.rs
  src/schema/io_thrift/to_thrift.rs
  src/schema/types/converted_type.rs
  src/schema/types/physical_type.rs
  src/statistics/binary.rs
  src/statistics/boolean.rs
  src/statistics/fixed_len_binary.rs
  src/statistics/primitive.rs
  src/write/column_chunk.rs
  src/write/file.rs
  src/write/indexes/serialize.rs
  src/write/indexes/write.rs
  src/write/page.rs
  src/write/row_group.rs
  src/write/stream.rs
  tests/it/read/mod.rs
Labels: bug

#175 Improved coverage report
  .github/workflows/coverage.yml
  .github/workflows/test.yml
Labels: testing

#174 Optional `async`
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  Cargo.toml
  src/read/mod.rs
  src/read/page/mod.rs
  src/write/column_chunk.rs
  src/write/indexes/write.rs
  src/write/mod.rs
  src/write/page.rs
  src/write/row_group.rs
Labels: backwards-incompatible

#179 Fixed error in encoding large bitpacked deltas
  src/encoding/delta_bitpacked/encoder.rs
  src/encoding/delta_bitpacked/mod.rs
Labels: bug

#176 Improved bitpacking
  Cargo.toml
  benches/decode_bitpacking.rs
  src/encoding/bitpacked/decode.rs
  src/encoding/bitpacked/encode.rs
  src/encoding/bitpacked/mod.rs
  src/encoding/bitpacked/pack.rs
  src/encoding/bitpacked/unpack.rs
  src/encoding/bitpacking.rs
  src/encoding/delta_bitpacked/decoder.rs
  src/encoding/delta_bitpacked/encoder.rs
  src/encoding/delta_bitpacked/mod.rs
  src/encoding/hybrid_rle/decoder.rs
  src/encoding/hybrid_rle/encoder.rs
  src/encoding/hybrid_rle/mod.rs
  src/encoding/mod.rs
  src/write/file.rs
  tests/it/read/primitive_nested.rs
Labels: backwards-incompatible

#180 Improved decoding documentation
  src/encoding/delta_bitpacked/decoder.rs
  src/encoding/hybrid_rle/bitmap.rs
  src/encoding/hybrid_rle/decoder.rs
  src/encoding/hybrid_rle/mod.rs
  src/encoding/mod.rs
Labels: documentation

#181 Improved `Error`
  src/compression.rs
  src/deserialize/binary.rs
  src/deserialize/boolean.rs
  src/deserialize/fixed_len.rs
  src/deserialize/native.rs
  src/deserialize/utils.rs
  src/encoding/plain_byte_array.rs
  src/error.rs
  src/indexes/intervals.rs
  src/metadata/column_chunk_metadata.rs
  src/metadata/row_metadata.rs
  src/metadata/schema_descriptor.rs
  src/page/mod.rs
  src/parquet_bridge.rs
  src/read/indexes/read.rs
  src/read/metadata.rs
  src/read/page/indexed_reader.rs
  src/read/page/reader.rs
  src/read/stream.rs
  src/schema/io_message/from_message.rs
  src/schema/io_thrift/from_thrift.rs
  src/schema/types/converted_type.rs
  src/schema/types/physical_type.rs
  src/schema/types/spec.rs
  src/statistics/boolean.rs
  src/statistics/fixed_len_binary.rs
  src/statistics/primitive.rs
  src/write/column_chunk.rs
  src/write/file.rs
  src/write/indexes/serialize.rs
  src/write/page.rs
  src/write/row_group.rs
  src/write/statistics.rs
  src/write/stream.rs
  tests/it/read/primitive.rs
Labels: backwards-incompatible

#183 Added DELTA_BYTE_ARRAY encoder
  src/encoding/delta_byte_array/decoder.rs
  src/encoding/delta_byte_array/encoder.rs
  src/encoding/delta_byte_array/mod.rs
Labels: feature

#184 FixedLenByteArray max_precision integer overflow
  src/schema/types/spec.rs
Labels: bug

#187 Fixed error in `FilteredHybridBitmapIter`'s trait bounds
  src/deserialize/filtered_rle.rs
  src/metadata/column_order.rs
  tests/it/read/deserialize.rs
Labels: bug

#189 Fixed edge cases delta encoder
  src/encoding/delta_bitpacked/encoder.rs
Labels: bug

#190 Improved doc generation to include features
  .github/workflows/docs.yml
  Cargo.toml
  guide/src/README.md
  src/read/page/indexed_reader.rs
  src/read/page/reader.rs
  src/write/file.rs
Labels: documentation

#188 Replaced panics by errors on invalid pages
  src/compression.rs
  src/error.rs
  src/read/compression.rs
  src/read/page/reader.rs
Labels: enhancement

#191 Removed `EncodedPage`
  src/page/mod.rs
  src/write/compression.rs
  tests/it/write/binary.rs
  tests/it/write/mod.rs
  tests/it/write/primitive.rs
Labels: backwards-incompatible
