Repository jorgecarleitao/parquet2, pull requests merged in 2022-04, with the labels that each got.

#116 Added tests for reducing statistics
  src/schema/types/logical_to_converted.rs
  src/schema/types/mod.rs
  src/statistics/primitive.rs
  src/write/statistics.rs
Labels: testing

#122 Fix minimum version for LZ4
  Cargo.toml
Labels: bug

#120 Added specialized deserialization of one-level filtered pages
  src/deserialize/filtered_rle.rs
  src/deserialize/hybrid_rle.rs
  src/deserialize/mod.rs
  src/deserialize/utils.rs
  tests/it/read/deserialize.rs
  tests/it/read/mod.rs
  tests/it/read/utils.rs
Labels: enhancement

#123 Made offsets be always written
  src/write/file.rs
Labels: enhancement

#124 Add optional LZ4 flex
  .github/workflows/test.yml
  Cargo.toml
  src/compression.rs
  src/error.rs
Labels: feature

#127 Made `.end` not consume the parquet `FileWriter`
  src/write/file.rs
  tests/it/write/indexes.rs
  tests/it/write/mod.rs
Labels: backwards-incompatible

#129 Improved perf of bitpacking decoding (3.5x)
  Cargo.toml
  benches/decode_bitpacking.rs
  src/encoding/bitpacking.rs
Labels: enhancement

#132 Added compression options/levels for GZIP and BROTLI codecs.
  src/compression.rs
  src/parquet_bridge.rs
  tests/it/write/mod.rs
Labels: feature

#133 Improved Integration test documentation and expanded tests
  README.md
  tests/it/read/mod.rs
  tests/write_pyarrow.py
Labels: testing
