Repository jorgecarleitao/parquet2, pull requests merged in 2022-05, with the labels that each got.

#140 Fixed error in compressing lz4raw with large offsets
  src/compression.rs
Labels: bug

#141 Lifted duplicated code to a function
  src/compression.rs
Labels: testing

#138 Fix potential misuse of FileWriter API's (sync + async)
  src/lib.rs
  src/read/metadata.rs
  src/read/stream.rs
  src/write/file.rs
  src/write/mod.rs
  src/write/stream.rs
  tests/it/write/indexes.rs
  tests/it/write/mod.rs
Labels: backwards-incompatible

#143 Improved read of metadata
  src/read/metadata.rs
  src/read/stream.rs
  tests/it/read/mod.rs
Labels: enhancement

#145 Removed unused cargo feature
  .github/workflows/test.yml
  Cargo.toml
  src/encoding/delta_bitpacked/decoder.rs
  src/read/mod.rs
  src/read/page/mod.rs
  src/write/mod.rs
  src/write/page.rs
  tests/it/read/primitive.rs
Labels: backwards-incompatible
